---
cores:

  project_io_core:
    type: io

    inputs:
      val21_in: 32
      val22_in: 32
      val23_in: 32
      val24_in: 32

    outputs:
      val1_out: 32
      val2_out: 32
      val3_out: 32
      val4_out: 32
      val5_out: 32
      val6_out: 32
      val7_out: 32
      val8_out: 32
      val9_out: 32
      val10_out: 32
      val11_out: 32
      val12_out: 32
      val13_out: 32
      val14_out: 32
      val15_out: 32
      val16_out: 32
      val17_out: 32
      val18_out: 32
      val19_out: 32
      val20_out: 32

uart:
  port: "/dev/cu.usbserial-88742923004D1"
  baudrate: 3000000
  clock_freq: 100000000